#! /usr/bin/env python
# encoding: utf-8

NAME = 'pysoy'
DATE = 'unreleased'
VERSION = '1.0_beta3'
WEBSITE = 'http://www.pysoy.org/'
LICENSE = '''
    Copyright (C) 2006,2007,2008,2009,2010,2011,2012 Copyleft Games Group

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
'''
import sys, os
from waflib.Utils import subprocess

top = '.'
out = 'build'
PY_MIN_VERSION = (3, 1, 0)

def options(opt):
    opt.load('compiler_c')

    # Unit testing
    opt.add_option('--runtests', dest='runTests', default=False, 
        action='store_true', help='run unit tests found in tests/')
    opt.load('waf_unit_test')


def configure(conf) :
    # Check for a C compiler, valac, and orcc
    conf.load('compiler_c')
    
    # Unit testing
    conf.load('waf_unit_test')

    # Check for python
    conf.load('python')
    conf.check_python_headers()

    # Sphinx
    conf.find_program("sphinx-build", var="SPHINX_BUILD")
    
    # Write configuration to disk

    conf.check_cfg(package='soy-1.0', uselib_store='SOY',
                   mandatory=True, args='--cflags --libs')
    conf.check_cfg(package='x11', uselib_store='X11', 
                   mandatory=True, args='--cflags --libs')
    conf.check_cfg(package='xi', uselib_store='XI',
                   mandatory=True, args='--cflags --libs')
    conf.check_cfg(package='xxf86vm', uselib_store='XXF86VM', 
                   mandatory=True, args='--cflags --libs')
    conf.check_cfg(package='egl', uselib_store='EGL',
                   mandatory=True, args='--cflags --libs')


    # Set the package to pysoy
    conf.env['PACKAGE'] = 'pysoy'

    # Set platform
    from platform import system; conf.env[system().upper()] = 1


def build(bld) :
    # Defines for .pc
    bld.define('PACKAGE', NAME)
    bld.define('VERSION', VERSION)

    # Install config.h in /usr/local/include/pysoy
    bld.install_files('${PREFIX}/include/pysoy', out + '/config.h')
    bld.recurse('src include')
    
    # Unit testing
    if bld.options.runTests:
        bld.recurse('tests')
        from waflib.Tools import waf_unit_test
        bld.add_post_fun(waf_unit_test.summary)


